# application-test-example.yml
# ⚠ 이 파일은 예시입니다.
# 'application-test.yml'로 이름을 바꾸고
# 프로젝트에 맞게 값을 입력하여 사용하세요.

spring:
  datasource: # Github Actions의 build 과정 중 test 의 db 연결을 위해 추가
    driver-class-name: org.h2.Driver
    url: ${SPRING_DATASOURCE_URL_H2}
    username: ${SPRING_DATASOURCE_USERNAME_H2}
    password: ${SPRING_DATASOURCE_PASSWORD_H2}
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  data: # 외부 의존성 끄기
    redis:
      host: ${SPRING_REDIS_HOST}
      port: ${SPRING_REDIS_PORT}